helm_owner               = "isaiah4748"
argocd_values_file       = "helm-values/argocd.yaml"
external_dns_values_file = "helm-values/external-dns.yaml"
cert_manager_values_file = "helm-values/cert-manager.yaml"
iam_user_arn             = "arn:aws:iam::282378667097:user/isaiah4748"
iam_user_name            = "isaiah4748"
cluster_name             = "eks-cluster"
region                   = "eu-west-2"
