apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: imichael1403@gmail.com
    privateKeySecretRef:
      name: issuer
    solvers:
      - selector:
          dnsZones:
            - "lab.isaiahmichael.com"
        dns01:
          route53:
            region: eu-west-2
            hostedZoneID: Z1R8UBAEXAMPLE
      - http01:
          ingress:
            class: nginx


      
      