apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hub
  namespace: apps
  labels:
    app: app-hub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-hub
  template:
    metadata:
      labels:
        app: app-hub
    spec:
      containers:
        - name: flask-app
          image: 282378667097.dkr.ecr.eu-west-2.amazonaws.com/flask-eks-docs:latest
          ports:
            - containerPort: 5001
              name: http
          env:
            - name: PORT
              value: "5001"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: the-app-hub
  namespace: apps
  labels:
    app: app-hub
spec:
  selector:
    app: app-hub
  ports:
    - port: 80
      targetPort: 5001
      name: http
  type: ClusterIP
