apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hub
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-hub
  template:
    metadata:
      labels:
        app: app-hub
    spec:
      containers:
        - name: flask-mysql
          image: isaiah4748/flask-mysql
          ports:
            - containerPort: 5000  # Flask default port
---
apiVersion: v1
kind: Service
metadata:
  name: the-app-hub
  namespace: apps
spec:
  selector:
    app: app-hub
  ports:
    - port: 80
      targetPort: 5000  # Forward external 80 to container 5000
