apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-app-hub
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-app-hub
  template:
    metadata:
      labels:
        app: the-app-hub
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: the-app-hub
  namespace: apps
spec:
  selector:
    app: the-app-hub
  ports:
    - port: 80
      targetPort: 80
