apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-hub
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/isaiah1701/k8-eks.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-app-hub-ingress
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: "issuer"
spec:
  ingressClassName: nginx
  rules:
    - host: app.argocd.isaiahmichael.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: the-app-hub
                port:
                  number: 80
  tls:
    - hosts:
        - app.argocd.isaiahmichael.com
      secretName: the-app-hub-tls
