apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hub
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-hub
  template:
    metadata:
      labels:
        app: app-hub
    spec:
      containers:
        - name: istio-app
          image: istio/app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: the-app-hub
  namespace: apps
spec:
  selector:
    app: app-hub
  ports:
    - port: 80
      targetPort: 8080
