apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hub
  namespace: apps
  labels:
    app: app-hub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-hub
  template:
    metadata:
      labels:
        app: app-hub
    spec:
      containers:
      - name: app-hub
        image: 282378667097.dkr.ecr.eu-west-2.amazonaws.com/flask-eks-docs:latest
        imagePullPolicy: Always  # forces pulling latest image
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: the-app-hub
  namespace: apps
  labels:
    app: app-hub
spec:
  selector:
    app: app-hub
  ports:
    - port: 80
      targetPort: 5001
      name: http
  type: ClusterIP
