# Create letsencrypt-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Production Let's Encrypt server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for Let's Encrypt account (use your email)
    email: imichael1403@gmail.com
    # Private key secret for ACME account
    privateKeySecretRef:
      name: letsencrypt-prod
    # ACME challenge solver configuration
    solvers:
    - http01:
        ingress:
          class: nginx