# LETSENCRYPT CLUSTERISSUER - Configures Let's Encrypt certificate authority for automatic SSL
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod  # ClusterIssuer name referenced in ingress annotations
spec:
  acme:
    # LETS ENCRYPT SERVER - Production certificate authority endpoint
    server: https://acme-v02.api.letsencrypt.org/directory  # Production Let's Encrypt server
    
    # ACCOUNT CONFIGURATION - Let's Encrypt account settings
    email: imichael1403@gmail.com  # Contact email for certificate notifications and account
    
    # PRIVATE KEY STORAGE - Stores ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod  # Kubernetes secret to store Let's Encrypt account key
    
    # CHALLENGE SOLVERS - Methods to prove domain ownership
    solvers:
    - http01:  # HTTP-01 challenge method
        ingress:
          class: nginx  # Use NGINX ingress controller for challenge response