# Prometheus configuration
prometheus:
  prometheusSpec:
    # How long to keep metrics
    retention: 15d
    # Storage size
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "gp2"  # ADD: EKS default storage class
          resources:
            requests:
              storage: 20Gi
    # Monitor all namespaces
    serviceMonitorNamespaceSelector: {}  # CHANGED: Monitor all namespaces
    serviceMonitorSelector: {}
    ruleSelector: {}

# Grafana configuration
grafana:
  enabled: true
  adminPassword: admin123
  persistence:
    enabled: true
    storageClassName: "gp2"  # ADD: EKS storage class
    size: 10Gi
  # Don't create ingress here - we'll use separate file
  ingress:
    enabled: false

# Alert Manager
alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "gp2"  # ADD: EKS storage class
          resources:
            requests:
              storage: 2Gi

# Node Exporter
nodeExporter:
  enabled: true

# State Metrics
kubeStateMetrics:
  enabled: true