# Prometheus configuration
prometheus:
  prometheusSpec:
    # How long to keep metrics
    retention: 15d
    # Explicitly disable storage
    storageSpec: {}
    # Monitor all namespaces
    serviceMonitorNamespaceSelector: {}  # CHANGED: Monitor all namespaces
    serviceMonitorSelector: {}
    ruleSelector: {}

# Grafana configuration
grafana:
  enabled: true
  adminPassword: admin123
  # Explicitly disable persistence
  persistence:
    enabled: false
  # Don't create ingress here - we'll use separate file
  ingress:
    enabled: false

# Alert Manager - explicitly disable storage
alertmanager:
  enabled: true
  alertmanagerSpec: {}

# Node Exporter
nodeExporter:
  enabled: true

# State Metrics
kubeStateMetrics:
  enabled: true