# PROMETHEUS HELM VALUES - Configures monitoring stack with Prometheus and Grafana
prometheus:
  prometheusSpec:
    # How long to keep metrics
    retention: 15d  # Keep metrics data for 15 days
    # Explicitly disable storage
    storageSpec: {}  # Use ephemeral storage (no persistent volumes)
    # Monitor all namespaces
    serviceMonitorNamespaceSelector: {}  # Monitor services in all namespaces
    serviceMonitorSelector: {}  # Select all ServiceMonitor resources
    ruleSelector: {}  # Select all PrometheusRule resources for alerting

# GRAFANA CONFIGURATION - Dashboard and visualization platform
grafana:
  enabled: true  # Enable Grafana deployment
  adminPassword: admin123  # Default admin password for login
  
  # STORAGE CONFIGURATION - Use ephemeral storage
  persistence:
    enabled: false  # No persistent storage for dashboards/data
  
  # INGRESS CONFIGURATION - Disable built-in ingress
  ingress:
    enabled: false  # Use separate ingress manifest for custom configuration

# ALERTMANAGER CONFIGURATION - Handles alert routing and notifications
alertmanager:
  enabled: true  # Enable AlertManager for alert handling
  alertmanagerSpec: {}  # Use default configuration with ephemeral storage

# NODE EXPORTER - Collects hardware and OS metrics from nodes
nodeExporter:
  enabled: true  # Deploy DaemonSet to collect node-level metrics

# KUBE-STATE-METRICS - Exposes Kubernetes object metrics
kubeStateMetrics:
  enabled: true  # Monitor Kubernetes API objects (pods, deployments, etc.)