name: push to ECR and deploy to EKS to view flask app online 

on:
  push:
    branches:
      - main
    paths:
      - 'dockerFolder/**'

permissions:
  contents: read
  security-events: write
  actions: read

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: flask-eks-docs
  EKS_CLUSTER_NAME: eks-cluster 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd dockerFolder
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Security Scan - Trivy Vulnerability Check
      uses: aquasecurity/trivy-action@master
      continue-on-error: true  # Never fail the workflow
      with:
        image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        format: 'table'
        severity: 'CRITICAL,HIGH,MEDIUM,LOW'
        exit-code: '0'  # Never exit with error
      
    - name: Security Warning Banner
      run: |
        echo "⚠️ =================================================="
        echo "⚠️  SECURITY SCAN COMPLETED - CHECK RESULTS ABOVE"
        echo "⚠️  DEPLOYMENT WILL CONTINUE REGARDLESS OF FINDINGS"
        echo "⚠️  PLEASE REVIEW VULNERABILITIES FOR PRODUCTION USE"
        echo "⚠️ =================================================="

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" apps/app-backend.yaml
        kubectl apply -f apps/app-backend.yaml
        kubectl apply -f apps/app-hub.yaml
        kubectl rollout status deployment/app-hub -n apps --timeout=300s

    - name: Deployment Success
      run: |
        echo "✅ =================================================="
        echo "✅  DEPLOYMENT COMPLETED SUCCESSFULLY!"
        echo "✅  Flask app is now live at:"
        echo "✅  https://app.argocd.isaiahmichael.com"
        echo "✅ =================================================="
        kubectl get pods -n apps
        kubectl get svc -n apps
        kubectl get ingress -n apps



